=== Pandaliha/XML/src/orderSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema
xmlns:xsd="http://www.w3.org/2001/XMLSchema"
elementFormDefault="qualified">


<xsd:element name="order">
 <xsd:complexType>
 <xsd:sequence>
    <xsd:element name="total" type="xsd:decimal" />
    <xsd:element name="order-number" type="xsd:integer" />
     <xsd:element name="items">
     <xsd:complexType>
     <xsd:sequence>
    <xsd:element name="item" minOccurs="1" maxOccurs="unbounded">
     <xsd:complexType>
     <xsd:sequence>
        <xsd:element name="unit-price" type="xsd:decimal" />
        <xsd:element name="amount" minOccurs="1" />
        <xsd:element name="order-number" type="xsd:integer"  />
        <xsd:element name="total-price" type="xsd:decimal" />
     </xsd:sequence>
     </xsd:complexType>
     </xsd:element>
     </xsd:sequence>
     </xsd:complexType>
   </xsd:element>
     
     
    <xsd:element name="address" minOccurs="2" maxOccurs="2"> 
     <xsd:complexType>
     <xsd:sequence>
        <xsd:element name="title" type="xsd:string" minOccurs="0" />
         <xsd:element name="first-name" type="xsd:string" />
        <xsd:element name="last-name" type="xsd:string" />
        <xsd:element name="street" type="xsd:string" />
        <xsd:element name="house-number" type="xsd:integer" />
        <xsd:element name="zip" type="xsd:integer" />
        <xsd:element name="town" type="xsd:string" />
     </xsd:sequence>
     <xsd:attribute name="type" type="xsd:string" use="required"/>
     </xsd:complexType>
    </xsd:element>
     
     </xsd:sequence>
     </xsd:complexType>
    </xsd:element>
    

</xsd:schema>

=== Pandaliha/XML/src/order.xml
<?xml version="1.0" encoding="UTF-8"?>

<order
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="orderSchema.xsd">
    <total>45.00</total>
    <order-number>57822394</order-number>
    <items>
        <!-- at least one item -->
        <item>
            <unit-price>10.0</unit-price>
            <amount>2</amount>
            <order-number>42</order-number>
            <total-price>20.0</total-price> <!-- optional -->
        </item>
        <item>
            <unit-price>98.0</unit-price>
            <amount>1</amount>
            <order-number>24</order-number>
            <total-price>98.0</total-price>
        </item>
    </items>
    <!-- exactly two addresses -->
    <address type="shipping">
        <first-name>Max</first-name>
        <last-name>Mustermann</last-name>
        <street>Musterstrasse</street>
        <house-number>1</house-number>
        <zip>23456</zip>
        <town>Muster</town>
    </address>
    <address type="billing">
        <title>Dr.</title> <!-- optional -->
        <first-name>Anna</first-name>
        <last-name>Anders</last-name>
        <street>Anderestraße</street>
        <house-number>7</house-number>
        <zip>89012</zip>
        <town>Anderswo</town>
    </address>
</order>
